spring.application.name=ms-carroCompras

server.port=8086

#Configuración de la Base de Datos (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/carro_compras_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Mishes2026

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Clave secreta para JWT
jwt.secret=TuClaveSecretaSuperSeguraParaDuocUC2026!