server.port=8080
spring.application.name=api-gateway

# 1. ENRUTAMIENTO HACIA MS-USUARIO (Puerto 8081)
spring.cloud.gateway.routes[0].id=ms-usuario-route
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/usuarios/**,/api/auth/**

# 2. ENRUTAMIENTO HACIA MS-CLIENTE (Puerto 8082)
spring.cloud.gateway.routes[1].id=ms-cliente-route
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/clientes/**

# 3. ENRUTAMIENTO HACIA MS-PEDIDO (Puerto 8084)
spring.cloud.gateway.routes[2].id=ms-pedido-route
spring.cloud.gateway.routes[2].uri=http://localhost:8084
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/pedidos/**


# 4. ENRUTAMIENTO HACIA MS-PAGO (Puerto 8083)
spring.cloud.gateway.routes[3].id=ms-pago-route
spring.cloud.gateway.routes[3].uri=http://localhost:8083
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/pagos/**


# 5. Ruta para el Microservicio de Productos (Puerto 8085)
spring.cloud.gateway.routes[4].id=ms-producto-route
spring.cloud.gateway.routes[4].uri=http://localhost:8085
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/productos/**

# 6. Ruta para el Microservicio de Carro de Compras (Puerto 8086)
spring.cloud.gateway.routes[5].id=ms-carro-route
spring.cloud.gateway.routes[5].uri=http://localhost:8086
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/carrito/**


# ==========================================
# CONFIGURACIÓN SWAGGER CENTRALIZADO
# ==========================================
springdoc.swagger-ui.urls[0].name=1. Microservicio de Usuarios
springdoc.swagger-ui.urls[0].url=http://localhost:8081/v3/api-docs

springdoc.swagger-ui.urls[1].name=4. Microservicio de Clientes
springdoc.swagger-ui.urls[1].url=http://localhost:8082/v3/api-docs

springdoc.swagger-ui.urls[2].name=5. Microservicio de Pagos
springdoc.swagger-ui.urls[2].url=http://localhost:8083/v3/api-docs

springdoc.swagger-ui.urls[3].name=3. Microservicio de Pedidos
springdoc.swagger-ui.urls[3].url=http://localhost:8084/v3/api-docs

springdoc.swagger-ui.urls[4].name=2. Microservicio de Productos
springdoc.swagger-ui.urls[4].url=http://localhost:8085/v3/api-docs

springdoc.swagger-ui.urls[5].name=6. Microservicio de Carro de Compras
springdoc.swagger-ui.urls[5].url=http://localhost:8086/v3/api-docs